version: '3.8'

services:
  backend:
    container_name: clearrouter-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgresql://postgres:bL735U6L3S2Q9iPB@db.mphgbpaitzdncedvovzz.supabase.co:5432/postgres?sslmode=require"
      NODE_ENV: "production"
      PORT: "8080"
    extra_hosts:
      - "db.mphgbpaitzdncedvovzz.supabase.co:34.132.72.40"?sslmode=require
    networks:
      - clear-router-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    container_name: clearrouter-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - clear-router-network

networks:
  clear-router-network:
    driver: bridge
