services:
  backend:
    container_name: clearrouter-backend-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev   
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./apps/backend:/app 
    networks:
      - clearrouter-net

networks:
  clearrouter-net:
    driver: bridge
